# action.yml
name: 'Issue comment tag'
author: 'Rob Bos'
description: 'Tag a team in an issue comment.'
branding:
  icon : alert-circle
  color: blue
inputs:
  team:
    description: 'The tag of the team to mention in the issue comment'
    required: true
  issue:
    description: 'The issue number to create a new comment in'
    required: true
  GITHUB_TOKEN:
    description: 'The GitHub token to use to create a new comment with. Use ${{ secrets.GITHUB_TOKEN }} to inject it'
    required: true
runs:
  using: 'node12'
  main: 'dist/main.js'